name: Build TWRP SM-T113NU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y repo git

    - name: Init TWRP source
      run: |
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync

    - name: Clone device tree
      run: |
        git clone https://github.com/sixito007/android_device_samsung_goyave3g
    - name: Build recovery
      run: |
        source build/envsetup.sh
        lunch omni_t113nu-eng
        mka recoveryimage

    - name: Upload recovery
      uses: actions/upload-artifact@v3
      with:
        name: twrp
        path: out/target/product/t113nu/recovery.img
